const firstName = "Bob";
const lastName = "Marly";
const age = 32;
const dateOfBirth = "12/05/1854";
const address = "London, 1St Street 32";
console.log('name: ', firstName);
console.log('last name: ', lastName);
console.log('age: ', age);
console.log('date of birth: ', dateOfBirth);
console.log('address: ', address);