var firstName = "Bob";
var lastName = "Marly";
var age = 32;
var dateOfBirth = "12/05/1854";
var address = "London, 1St Street 32";
console.log('name: ', firstName);
console.log('last name: ', lastName);
console.log('age: ', age);
console.log('date of birth: ', dateOfBirth);
console.log('address: ', address);