let firstName = "Bob";
let lastName = "Marly";
let age = 32;
let dateOfBirth = "12/05/1854";
let address = "London, 1St Street 32";
console.log('name: ', firstName);
console.log('last name: ', lastName);
console.log('age: ', age);
console.log('date of birth: ', dateOfBirth);
console.log('address: ', address);